jwt:
  secret: 'secret '

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/support_portal
    username: root
    password: letmein
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
